---
- name: Tuesday Challenge
  hosts: planetexpress
  gather_facts: yes

  tasks:
   - name: creating a file
     file:
        dest: challenge
        state: directory
       
   - name: create a file
     copy: 
       dest: challenge/challengefile.txt
       content: "fasfsadfas"
